-- Generated by CodeFirst.ISqlGenerator.
CREATE TABLE "{$TableName$}" (
  "Id" BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  "UserId" BIGINT NOT NULL COMMENT '用户id',
  "UserName" VARCHAR(50) COMMENT '用户名称',
  "Age" INT NOT NULL DEFAULT 18 COMMENT '年龄',
  "Sex" INT NOT NULL COMMENT '性别',
  "PhoneNumber" VARCHAR(50) COMMENT '电话号码',
  "Email" VARCHAR(50) DEFAULT 'user@sample.com' COMMENT '邮箱',
  "IsVip" BIT NOT NULL DEFAULT 1 COMMENT '是否VIP用户',
  "IsBlack" BIT NOT NULL DEFAULT 0 COMMENT '是否黑名单用户',
  "Country" INT NOT NULL DEFAULT 1 COMMENT '国家',
  "AccountBalance" DECIMAL(18,2) NOT NULL DEFAULT 999.98 COMMENT '账户余额',
  "AccountBalance2" DECIMAL(18,2) NOT NULL DEFAULT 9.98 COMMENT '账户余额',
  "Status" INT NOT NULL DEFAULT 0 COMMENT '状态',
  "Remark" VARCHAR(255) COMMENT '备注',
  "CreateTime" DATETIME NOT NULL COMMENT '创建时间',
  "UpdateTime" DATETIME COMMENT '更新时间',
  PRIMARY KEY ("Id")
) COMMENT '测试表';