CREATE TABLE "{$TableName$}" (
	"Id" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"UserId" BIGINT NOT NULL,
	"UserName" VARCHAR(50),
	"Age" INTEGER NOT NULL DEFAULT 0,
	"Sex" INTEGER NOT NULL DEFAULT 0,
	"PhoneNumber" VARCHAR(50),
	"Email" VARCHAR(50),
	"IsVip" INTEGER NOT NULL DEFAULT 0,
	"IsBlack" INTEGER NOT NULL DEFAULT 0,
	"Country" INTEGER NOT NULL DEFAULT 0,
	"AccountBalance" DECIMAL NOT NULL DEFAULT 0,
	"AccountBalance2" DECIMAL NOT NULL DEFAULT 0,
	"Status" INTEGER NOT NULL DEFAULT 0,
	"Remark" VARCHAR(255),
	"CreateTime" TIMESTAMP NOT NULL,
	"UpdateTime" TIMESTAMP,
	CONSTRAINT "PK_{$TableName$}" PRIMARY KEY ("Id")
);

--CREATE TABLE "TEST" (
--	"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
--	"USER_ID" BIGINT NOT NULL,
--	"USER_NAME" VARCHAR(50),
--	"AGE" INTEGER NOT NULL DEFAULT 0,
--	"SEX" INTEGER NOT NULL DEFAULT 0,
--	"PHONE_NUMBER" VARCHAR(50),
--	"EMAIL" VARCHAR(50),
--	"IS_VIP" INTEGER NOT NULL DEFAULT 0,
--	"IS_BLACK" INTEGER NOT NULL DEFAULT 0,
--	"COUNTRY" INTEGER NOT NULL DEFAULT 0,
--	"ACCOUNT_BALANCE" DECIMAL NOT NULL DEFAULT 0,
--	"ACCOUNT_BALANCE2" DECIMAL NOT NULL DEFAULT 0,
--	"STATUS" INTEGER NOT NULL DEFAULT 0,
--	"REMARK" VARCHAR(255),
--	"CREATE_TIME" TIMESTAMP NOT NULL,
--	"UPDATE_TIME" TIMESTAMP,
--	CONSTRAINT "PK_TEST" PRIMARY KEY ("ID")
--);