CREATE SEQUENCE SQ_{$TableName$};
-- ### MultiSqlSeparator ###
CREATE TABLE {$TableName$} (
  Id BIGINT PRIMARY KEY DEFAULT nextval('SQ_{$TableName$}'),
  UserId BIGINT NOT NULL,
  UserName VARCHAR(50),
  Age INTEGER NOT NULL DEFAULT 0,
  Sex TINYINT NOT NULL DEFAULT 0,
  PhoneNumber VARCHAR(50),
  Email VARCHAR(50),
  IsVip BOOLEAN NOT NULL DEFAULT FALSE,
  IsBlack BOOLEAN NOT NULL DEFAULT FALSE,
  Country INTEGER NOT NULL DEFAULT 0,
  AccountBalance DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  AccountBalance2 DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  Status INTEGER NOT NULL DEFAULT 0,
  Remark VARCHAR(255),
  CreateTime TIMESTAMP NOT NULL,
  UpdateTime TIMESTAMP
);