-- Generated by CodeFirst.ISqlGenerator.
CREATE TABLE "{$TableName$}" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "UserId" BIGINT NOT NULL,
  "UserName" BLOB SUB_TYPE TEXT,
  "Age" INTEGER NOT NULL DEFAULT 18,
  "Sex" INTEGER NOT NULL,
  "PhoneNumber" BLOB SUB_TYPE TEXT,
  "Email" BLOB SUB_TYPE TEXT DEFAULT 'user@sample.com',
  "IsVip" BOOLEAN NOT NULL DEFAULT 1,
  "IsBlack" BOOLEAN NOT NULL DEFAULT 0,
  "Country" INTEGER NOT NULL DEFAULT 1,
  "AccountBalance" DECIMAL(18,2) NOT NULL DEFAULT 999.98,
  "AccountBalance2" DECIMAL(18,2) NOT NULL DEFAULT 9.98,
  "Status" INTEGER NOT NULL DEFAULT 0,
  "Remark" BLOB SUB_TYPE TEXT,
  "CreateTime" TIMESTAMP NOT NULL,
  "UpdateTime" TIMESTAMP,
  CONSTRAINT "PK_{$TableName$}" PRIMARY KEY ("Id")
);
-- ### MultiSqlSeparator ###
COMMENT ON TABLE "{$TableName$}" IS '测试表';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."Id" IS '自增主键';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."UserId" IS '用户id';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."UserName" IS '用户名称';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."Age" IS '年龄';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."Sex" IS '性别';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."PhoneNumber" IS '电话号码';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."Email" IS '邮箱';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."IsVip" IS '是否VIP用户';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."IsBlack" IS '是否黑名单用户';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."Country" IS '国家';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."AccountBalance" IS '账户余额';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."AccountBalance2" IS '账户余额';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."Status" IS '状态';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."Remark" IS '备注';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."CreateTime" IS '创建时间';
-- ### MultiSqlSeparator ###
COMMENT ON COLUMN "{$TableName$}"."UpdateTime" IS '更新时间';