CREATE TABLE "{$TableName$}" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId" BIGINT NOT NULL,
    "UserName" BLOB SUB_TYPE TEXT,
    "Age" INTEGER NOT NULL,
    "Sex" INTEGER NOT NULL,
    "PhoneNumber" BLOB SUB_TYPE TEXT,
    "Email" BLOB SUB_TYPE TEXT,
    "IsVip" BOOLEAN NOT NULL,
    "IsBlack" BOOLEAN NOT NULL,
    "Country" INTEGER NOT NULL,
    "AccountBalance" DECIMAL(18,2) NOT NULL,
    "AccountBalance2" DECIMAL(18,2) NOT NULL,
    "Status" INTEGER NOT NULL,
    "Remark" BLOB SUB_TYPE TEXT,
    "CreateTime" TIMESTAMP NOT NULL,
    "UpdateTime" TIMESTAMP,
    CONSTRAINT "PK_{$TableName$}" PRIMARY KEY ("Id")
);