CREATE TABLE [{$TableName$}] (
    [Id] AUTOINCREMENT NOT NULL,
    [UserId] LONG NOT NULL,
    [UserName] VARCHAR(50),
    [Age] INTEGER DEFAULT 0 NOT NULL,
    [Sex] SMALLINT DEFAULT 0 NOT NULL,
    [PhoneNumber] VARCHAR(20),
    [Email] VARCHAR(50),
    [IsVip] BIT DEFAULT 0 NOT NULL,
    [IsBlack] BIT DEFAULT 0 NOT NULL,
    [Country] SMALLINT DEFAULT 0 NOT NULL,
    [AccountBalance] DECIMAL(18,2) DEFAULT 0 NOT NULL,
    [AccountBalance2] DECIMAL(18,2) DEFAULT 0 NOT NULL,
    [Status] SMALLINT DEFAULT 0 NOT NULL,
    [Remark] VARCHAR(255),
    [CreateTime] TIMESTAMP DEFAULT NOW() NOT NULL,
    [UpdateTime] TIMESTAMP,
    CONSTRAINT [PK_{$TableName$}] PRIMARY KEY ([Id])
);