CREATE TABLE "{$TableName$}" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "UserName" text NULL,
    "Age" integer NOT NULL,
    "Sex" integer NOT NULL,
    "PhoneNumber" text NULL,
    "Email" text NULL,
    "IsVip" boolean NOT NULL,
    "IsBlack" boolean NOT NULL,
    "Country" integer NOT NULL,
    "AccountBalance" numeric NOT NULL,
    "AccountBalance2" numeric NOT NULL,
    "Status" integer NOT NULL,
    "Remark" text NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    "UpdateTime" timestamp with time zone NULL,
    CONSTRAINT "PK_{$TableName$}" PRIMARY KEY ("Id")
);