-- Generated by CodeFirst.ISqlGenerator.
CREATE TABLE "{$TableName$}" (
  "Id" INT8 AUTO_INCREMENT NOT NULL,
  "UserId" INT8 NOT NULL,
  "UserName" CLOB,
  "Age" INT4 NOT NULL DEFAULT 18,
  "Sex" INT4 NOT NULL,
  "PhoneNumber" CLOB,
  "Email" CLOB DEFAULT 'user@sample.com',
  "IsVip" BOOL NOT NULL DEFAULT 1,
  "IsBlack" BOOL NOT NULL DEFAULT 0,
  "Country" INT4 NOT NULL DEFAULT 1,
  "AccountBalance" DECIMAL(18,2) NOT NULL DEFAULT 999.98,
  "AccountBalance2" DECIMAL(18,2) NOT NULL DEFAULT 9.98,
  "Status" INT4 NOT NULL DEFAULT 0,
  "Remark" CLOB,
  "CreateTime" TIMESTAMP NOT NULL,
  "UpdateTime" TIMESTAMP,
  CONSTRAINT "PK_{$TableName$}" PRIMARY KEY ("Id")
);