-- Generated by CodeFirst.ISqlGenerator.
CREATE TABLE [{$TableName$}] (
  [Id] bigint NOT NULL IDENTITY,
  [UserId] bigint NOT NULL,
  [UserName] nvarchar(50),
  [Age] int NOT NULL DEFAULT 18,
  [Sex] int NOT NULL,
  [PhoneNumber] nvarchar(50),
  [Email] nvarchar(50) DEFAULT 'user@sample.com',
  [IsVip] bit NOT NULL DEFAULT 1,
  [IsBlack] bit NOT NULL DEFAULT 0,
  [Country] int NOT NULL DEFAULT 1,
  [AccountBalance] decimal(18,2) NOT NULL DEFAULT 999.98,
  [AccountBalance2] decimal(18,2) NOT NULL DEFAULT 9.98,
  [Status] int NOT NULL DEFAULT 0,
  [Remark] nvarchar(255),
  [CreateTime] datetime2 NOT NULL,
  [UpdateTime] datetime2,
  CONSTRAINT [PK_{$TableName$}] PRIMARY KEY ([Id])
);
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'测试表', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'自增主键', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'Id';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'用户id', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'UserId';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'用户名称', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'UserName';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'年龄', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'Age';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'性别', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'Sex';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'电话号码', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'PhoneNumber';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'邮箱', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'Email';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否VIP用户', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'IsVip';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否黑名单用户', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'IsBlack';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'国家', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'Country';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'账户余额', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'AccountBalance';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'账户余额', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'AccountBalance2';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'状态', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'Status';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'备注', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'Remark';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'CreateTime';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'更新时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'{$TableName$}', @level2type=N'COLUMN',@level2name=N'UpdateTime';