-- Generated by CodeFirst.ISqlGenerator.
CREATE TABLE "{$TableName$}" (
  "Id" bigint IDENTITY(1,1) COMMENT '自增主键',
  "UserId" bigint NOT NULL COMMENT '用户id',
  "UserName" varchar(50) COMMENT '用户名称',
  "Age" int NOT NULL DEFAULT 18 COMMENT '年龄',
  "Sex" int NOT NULL COMMENT '性别',
  "PhoneNumber" varchar(50) COMMENT '电话号码',
  "Email" varchar(50) DEFAULT 'user@sample.com' COMMENT '邮箱',
  "IsVip" boolean NOT NULL DEFAULT true COMMENT '是否VIP用户',
  "IsBlack" boolean NOT NULL DEFAULT false COMMENT '是否黑名单用户',
  "Country" int NOT NULL DEFAULT 1 COMMENT '国家',
  "AccountBalance" decimal(18,2) NOT NULL DEFAULT 999.98 COMMENT '账户余额',
  "AccountBalance2" decimal(18,2) NOT NULL DEFAULT 9.98 COMMENT '账户余额',
  "Status" int NOT NULL DEFAULT 0 COMMENT '状态',
  "Remark" varchar(255) COMMENT '备注',
  "CreateTime" timestamp NOT NULL COMMENT '创建时间',
  "UpdateTime" timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY ("Id")
) COMMENT '测试表';