<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <WarningsAsErrors>$(WarningsAsErrors);MSTEST0017;MSTEST0044</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
    <PackageReference Include="MySql.Data" Version="26.7.0" />
    <ProjectReference Include="..\..\src\Sean.Core.DbRepository\Sean.Core.DbRepository.csproj" />
    <ProjectReference Include="..\..\src\Sean.Core.DbRepository.Dapper\Sean.Core.DbRepository.Dapper.csproj" />
  </ItemGroup>
</Project>
