using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Sean.Core.DbRepository.Extensions;

namespace Sean.Core.DbRepository.CodeFirst;

public class SqlGeneratorForOracle : BaseSqlGenerator
{
    public SqlGeneratorForOracle() : base(DatabaseType.Oracle)
    {
    }

    protected virtual string ConvertFieldType(EntityFieldInfo fieldInfo)
    {
        if (!string.IsNullOrWhiteSpace(fieldInfo.FieldTypeName))
        {
            return fieldInfo.FieldTypeName;
        }

        var underlyingType = Nullable.GetUnderlyingType(fieldInfo.Property.PropertyType) ?? fieldInfo.Property.PropertyType;
        string result;
        switch (underlyingType)
        {
            case not null when underlyingType == typeof(long):
                result = "NUMBER(19)";
                break;
            case not null when underlyingType == typeof(int) || underlyingType.IsEnum:
                result = "NUMBER(10)";
                break;
            case not null when underlyingType == typeof(bool):
                result = "NUMBER(1)";
                break;
            case not null when underlyingType == typeof(string):
                {
                    result = fieldInfo.MaxLength.HasValue ? $"NVARCHAR2({fieldInfo.MaxLength.Value})" : "NVARCHAR2";
                    break;
                }
            case not null when underlyingType == typeof(DateTime):
                result = "TIMESTAMP(7)";
                break;
            case not null when underlyingType == typeof(decimal):
                {
                    result = fieldInfo.NumericPrecision.HasValue ? $"DECIMAL({fieldInfo.NumericPrecision.GetValueOrDefault()},{fieldInfo.NumericScale.GetValueOrDefault()})" : "DECIMAL";
                    break;
                }
            default:
                result = $"##{underlyingType.Name}##";
                break;
        }
        return result;
    }

    public override List<string> GetCreateTableSql(Type entityType, bool ignoreIfExists = false, Func<string, string> tableNameFunc = null)
    {
        var result = new List<string>();
        var sb = new StringBuilder();
        var entityInfo = entityType.GetEntityInfo();
        var tableName = tableNameFunc != null ? tableNameFunc(entityInfo.TableName) : entityInfo.TableName;
        sb.AppendLine("BEGIN");
        sb.AppendLine($"execute immediate 'CREATE TABLE {_dbType.MarkAsIdentifier(tableName)} (");
        var fieldInfoList = new List<string>();
        var sbFieldInfo = new StringBuilder();
        var fieldDescriptionDic = new Dictionary<string, string>();
        foreach (var fieldInfo in entityInfo.FieldInfos)
        {
            sbFieldInfo.Clear();
            if (!string.IsNullOrWhiteSpace(fieldInfo.FieldDescription))
            {
                fieldDescriptionDic.Add(fieldInfo.FieldName, fieldInfo.FieldDescription);
            }
            sbFieldInfo.Append($"  {_dbType.MarkAsIdentifier(fieldInfo.FieldName)} {ConvertFieldType(fieldInfo)}");
            if (fieldInfo.IsIdentityField)
            {
                sbFieldInfo.Append(" GENERATED BY DEFAULT ON NULL AS IDENTITY");
            }
            if (fieldInfo.IsNotAllowNull)
            {
                sbFieldInfo.Append(" NOT NULL");
            }
            if (fieldInfo.FieldDefaultValue != null)
            {
                sbFieldInfo.Append($" DEFAULT {ConvertFieldDefaultValue(fieldInfo.FieldDefaultValue)?.Replace("'", "''")}");
            }
            fieldInfoList.Add(sbFieldInfo.ToString());
        }
        if (entityInfo.FieldInfos.Any(c => c.IsPrimaryKey))
        {
            fieldInfoList.Add($"  PRIMARY KEY ({string.Join(",", entityInfo.FieldInfos.Where(c => c.IsPrimaryKey).Select(c => _dbType.MarkAsIdentifier(c.FieldName)).ToList())})");
        }
        sb.AppendLine(string.Join($",{Environment.NewLine}", fieldInfoList));
        sb.AppendLine(")';");
        if (!string.IsNullOrWhiteSpace(entityInfo.TableDescription))
        {
            sb.AppendLine($"execute immediate 'COMMENT ON TABLE {_dbType.MarkAsIdentifier(tableName)} IS ''{entityInfo.TableDescription}''';");
        }
        foreach (var kv in fieldDescriptionDic)
        {
            sb.AppendLine($"execute immediate 'COMMENT ON COLUMN {_dbType.MarkAsIdentifier(tableName)}.{_dbType.MarkAsIdentifier(kv.Key)} IS ''{kv.Value}''';");
        }
        var createIndexSql = GetCreateIndexSql(entityType, ignoreIfExists, tableName);
        createIndexSql?.ForEach(sql =>
        {
            sb.AppendLine($"execute immediate '{sql}';");
        });
        sb.Append("END;");
        result.Add(sb.ToString());
        return result;
    }

    public override List<string> GetUpgradeSql(Type entityType, Func<string, string> tableNameFunc = null)
    {
        var entityInfo = entityType.GetEntityInfo();
        var tableName = tableNameFunc != null ? tableNameFunc(entityInfo.TableName) : entityInfo.TableName;
        if (!IsTableExists(tableName))
        {
            return GetCreateTableSql(entityType, false, _ => tableName);
        }
        var missingTableFieldInfo = GetDbMissingTableFields(entityType, tableName);
        var result = new List<string>();
        var sb = new StringBuilder();
        sb.AppendLine("BEGIN");
        var fieldDescriptionDic = new Dictionary<string, string>();
        missingTableFieldInfo?.ForEach(fieldInfo =>
        {
            if (!string.IsNullOrWhiteSpace(fieldInfo.FieldDescription))
            {
                fieldDescriptionDic.Add(fieldInfo.FieldName, fieldInfo.FieldDescription);
            }
            sb.Append($"execute immediate 'ALTER TABLE {_dbType.MarkAsIdentifier(tableName)} ADD {_dbType.MarkAsIdentifier(fieldInfo.FieldName)} {ConvertFieldType(fieldInfo)}");
            if (fieldInfo.IsNotAllowNull)
            {
                sb.Append(" NOT NULL");
            }
            if (fieldInfo.FieldDefaultValue != null)
            {
                sb.Append($" DEFAULT {ConvertFieldDefaultValue(fieldInfo.FieldDefaultValue)}");
            }
            sb.AppendLine("';");
        });
        foreach (var kv in fieldDescriptionDic)
        {
            sb.AppendLine($"execute immediate 'COMMENT ON COLUMN {_dbType.MarkAsIdentifier(tableName)}.{_dbType.MarkAsIdentifier(kv.Key)} IS ''{kv.Value}''';");
        }
        sb.Append("END;");
        result.Add(sb.ToString());
        return result;
    }
}